services:
  #application - nextjs
  application:
    container_name: event-resource-manager-application
    image: node:lts-alpine
    ports:
      - 3000:3000
    volumes:
      - ./code:/home/node/code
    working_dir: /home/node/code/event-resource-manager-application

    command: "npm run dev"
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    tty: true
  #Unit Tests
  jest:
    container_name: event-resource-manager-jest
    image: node:lts-alpine
    working_dir: /home/node/code/event-resource-manager-application
    volumes:
      - ./code:/home/node/code
    depends_on:
      - backend
      - application
    environment:
      - NODE_ENV=test
    tty: true

    #command: "npm run testWatch"
  #MongoDB
  backend:
    container_name: event-resource-manager-backend
    image: mongo:latest
    restart: always
    environment:
      DB_NAME: event-resource-manager
      MONGO_INITDB_DATABASE: event-resource-manager
    ports:
      - 27017:27017
    volumes:
      - ./.docker/event-resource-manager-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
